let studentDetail =  {
    "id": 125,
    "user_id": null,
    "student_parent_id": 125,
    "uuid": "e1b325a7-c98a-3b95-8822-c2c431ba773a",
    "first_name": "Aarif",
    "middle_name": null,
    "last_name": "Chacko",
    "date_of_birth": "2003-07-22T18:30:00.000000Z",
    "birth_place": "Raipur",
    "gender": "male",
    "contact_number": 77037578624,
    "email": "aarif.chacko@example.com",
    "nationality": "Indian",
    "blood_group_id": 2,
    "religion_id": 4,
    "category_id": null,
    "caste_id": null,
    "student_photo": null,
    "mother_tongue": "Hindi",
    "unique_identification_number": 7960802538,
    "emergency_contact_name": "Saurabh Chacko",
    "emergency_contact_number": 13785808341,
    "present_address_line_1": "70, Nancy Apartments, NikitaGarh",
    "present_address_line_2": null,
    "present_city": "Raipur",
    "present_state": "Chhattisgarh",
    "present_zipcode": 492001,
    "present_country": "India",
    "same_as_present_address": 26,
    "permanent_address_line_1": null,
    "permanent_address_line_2": null,
    "permanent_city": null,
    "permanent_state": null,
    "permanent_zipcode": null,
    "permanent_country": null,
    "options": null,
    "created_at": null,
    "updated_at": "2019-09-16T02:19:26.000000Z",
    "present_address": "70, Nancy Apartments, NikitaGarh, Raipur, Chhattisgarh, 492001, India",
    "permanent_address": "",
    "name": "Aarif Chacko",
    "age": {
        "years": 16,
        "months": 11,
        "days": 11
    },
    "caste": null,
    "category": null,
    "religion": {
        "id": 4,
        "name": "Sikh"
    },
    "blood_group": {
        "id": 2,
        "name": "O+"
    },
    "student_records": [
        {
            "id": 119,
            "academic_session_id": 2,
            "admission_id": 119,
            "student_id": 125,
            "is_promoted": 0,
            "fee_allocation_id": 28,
            "batch_id": 42,
            "roll_number": 7,
            "date_of_entry": "2019-04-28T18:30:00.000000Z",
            "entry_remarks": "Seat allotted",
            "date_of_exit": null,
            "exit_remarks": null,
            "termination_reason": null,
            "upload_token": null,
            "options": null,
            "created_at": null,
            "updated_at": "2019-07-08T06:44:58.000000Z",
            "full_roll_number": "XA7",
            "batch": {
                "id": 42,
                "position": 0,
                "course_id": 28,
                "name": "Section A",
                "exam_observation_id": null,
                "exam_grade_id": null,
                "description": null,
                "options": {
                    "max_strength": 25,
                    "roll_number_prefix": "XA"
                },
                "created_at": "2019-09-15T10:50:48.000000Z",
                "updated_at": "2019-09-15T10:50:48.000000Z",
                "holidays_except": [],
                "course": {
                    "id": 28,
                    "position": 0,
                    "academic_session_id": 2,
                    "course_group_id": 9,
                    "name": "Grade X",
                    "description": null,
                    "options": {
                        "attendance_type": "daily",
                        "enable_registration": 1,
                        "enable_registration_fee": 1,
                        "registration_fee": 2000
                    },
                    "created_at": "2019-09-15T10:50:48.000000Z",
                    "updated_at": "2019-09-15T10:50:48.000000Z"
                }
            },
            "admission": {
                "id": 119,
                "prefix": "SM",
                "number": 119,
                "registration_id": 125,
                "batch_id": 42,
                "date_of_admission": "2019-04-28T18:30:00.000000Z",
                "admission_remarks": "Seat allotted",
                "options": null,
                "created_at": null,
                "updated_at": null,
                "admission_number": "SM119"
            },
            "academic_session": {
                "id": 2,
                "name": "Session 2019-20",
                "start_date": "2019-03-31T18:30:00.000000Z",
                "end_date": "2020-09-29T18:30:00.000000Z",
                "is_default": 1,
                "description": "Session 2019-20",
                "options": {
                    "transfer_certificate_format": "cbse1819",
                    "exam_report_analysis": 1,
                    "exam_report_analysis_student_token": "ins-1875659000004478224",
                    "exam_report_analysis_staff_token": "ins-1875659000004478040"
                },
                "created_at": "2019-09-15T07:32:01.000000Z",
                "updated_at": "2020-05-17T01:01:59.000000Z",
                "exam_report_analysis": true,
                "exam_report_analysis_staff_token": "ins-1875659000004478040",
                "exam_report_analysis_student_token": "ins-1875659000004478224"
            }
        }
    ],
    "parent": {
        "id": 125,
        "user_id": null,
        "first_guardian_name": "Aadil Chacko",
        "first_guardian_relation": "father",
        "first_guardian_date_of_birth": "1983-10-27T18:30:00.000000Z",
        "first_guardian_qualification": null,
        "first_guardian_occupation": null,
        "first_guardian_annual_income": null,
        "first_guardian_email": "aadil.chacko@example.com",
        "first_guardian_contact_number_1": 13785808341,
        "first_guardian_contact_number_2": null,
        "first_guardian_photo": null,
        "first_guardian_unique_identification_number": null,
        "second_guardian_name": "Richa Chacko",
        "second_guardian_relation": "mother",
        "third_guardian_name": null,
        "third_guardian_relation": null,
        "second_guardian_date_of_birth": "1993-02-25T18:30:00.000000Z",
        "second_guardian_qualification": null,
        "second_guardian_occupation": null,
        "second_guardian_annual_income": null,
        "second_guardian_email": "richa.chacko@example.com",
        "second_guardian_contact_number_1": null,
        "second_guardian_contact_number_2": null,
        "second_guardian_photo": null,
        "second_guardian_unique_identification_number": null,
        "options": null,
        "created_at": null,
        "updated_at": "2019-09-16T02:19:26.000000Z",
        "father_name": "Aadil Chacko",
        "mother_name": "Richa Chacko",
        "spouse_name": null,
        "user": null
    },
    "user": null
}
                                    