let employeedetail = {
   "id":6,
   "uuid":"130adc98-7f66-4da0-99c1-23869285c371",
   "prefix":null,
   "user_id":null,
   "code":5,
   "first_name":"Ajay",
   "middle_name":null,
   "last_name":"Soni",
   "date_of_birth":"1988-05-31T18:30:00.000000Z",
   "date_of_anniversary":null,
   "gender":"male",
   "marital_status":null,
   "contact_number":8876544332,
   "alternate_contact_number":null,
   "email":null,
   "alternate_email":null,
   "nationality":null,
   "blood_group_id":null,
   "religion_id":null,
   "category_id":null,
   "caste_id":null,
   "photo":null,
   "mother_tongue":null,
   "unique_identification_number":null,
   "father_name":"Devi Singh",
   "mother_name":"radha",
   "spouse_name":null,
   "emergency_contact_name":null,
   "emergency_contact_number":null,
   "present_address_line_1":null,
   "present_address_line_2":null,
   "present_city":null,
   "present_state":null,
   "present_zipcode":null,
   "present_country":null,
   "same_as_present_address":0,
   "permanent_address_line_1":null,
   "permanent_address_line_2":null,
   "permanent_city":null,
   "permanent_state":null,
   "permanent_zipcode":null,
   "permanent_country":null,
   "options":[

   ],
   "created_at":"2020-06-27T11:59:08.000000Z",
   "updated_at":"2020-07-06T14:52:54.000000Z",
   "present_address":"",
   "permanent_address":"",
   "name":"Ajay Soni",
   "age":{
      "years":32,
      "months":1,
      "days":4
   },
   "employee_code":5,
   "caste":null,
   "category":null,
   "religion":null,
   "blood_group":null,
   "employee_terms":[
      {
         "id":5,
         "employee_id":6,
         "date_of_joining":"2020-04-10",
         "date_of_leaving":null,
         "joining_remarks":null,
         "leaving_remarks":null,
         "upload_token":"c4866a59-52fd-4462-ac49-49c81f5bfd06",
         "options":[

         ],
         "created_at":"2020-06-27T11:59:08.000000Z",
         "updated_at":"2020-06-27T11:59:08.000000Z"
      }
   ],
   "employee_designations":[
      {
         "id":5,
         "employee_id":6,
         "designation_id":8,
         "department_id":2,
         "employee_term_id":5,
         "date_effective":"2020-04-10",
         "date_end":null,
         "remarks":null,
         "upload_token":"364da450-25e7-441a-a2fe-28f6e4b6b5e7",
         "options":[

         ],
         "created_at":"2020-06-27T11:59:08.000000Z",
         "updated_at":"2020-06-27T11:59:08.000000Z",
         "department":{
            "id":2,
            "name":"Academic Department",
            "description":"",
            "options":[

            ],
            "created_at":null,
            "updated_at":null
         },
         "designation":{
            "id":8,
            "employee_category_id":3,
            "name":"Primary Teacher",
            "is_teaching_employee":1,
            "top_designation_id":4,
            "description":null,
            "options":[

            ],
            "created_at":"2020-05-17T23:23:19.000000Z",
            "updated_at":"2020-05-17T23:23:19.000000Z",
            "employee_category":{
               "id":3,
               "name":"Teaching Staff",
               "description":null,
               "options":[

               ],
               "created_at":"2020-05-17T23:23:19.000000Z",
               "updated_at":"2020-05-17T23:23:19.000000Z"
            }
         }
      }
   ],
   "user":null
}